#app:
    #resource: '@AppBundle/Controller/'
    #type: annotation

forecast_simple:
    path: "/forecast/index"
    defaults: {_controller: AppBundle:Forecast:index}

forecast_param:
    path: "/forecast/{weather}"
    defaults: {_controller: AppBundle:Forecast:indexParam}

forecast_2_param:
    path: "/forecast/{weather}/{temperature}"
    defaults: {_controller: AppBundle:Forecast:index2Params, weather: cloudy, temperature: 15}

forecast_request_param:
    path: "/forecast/indexRequest/{weather}/{temperature}"
    defaults: {_controller: AppBundle:Forecast:indexRequest, weather: cloudy, temperature: 15}

redirect_index:
    path: "/redirect/index"
    defaults: {_controller: AppBundle:Redirect:index}

redirect_internal:
    path: "/internalredirect"
    defaults: {_controller: AppBundle:Redirect:internalRedirect}

redirect_internal_permanent:
    path: "/internalpermredirect"
    defaults: {_controller: AppBundle:Redirect:internalRedirectPermanent}

redirect_external:
    path: "/externalredirect"
    defaults: {_controller: AppBundle:Redirect:extenalRedirect}

get_temp:
    path: "/temperature/{id}"
    defaults: {_controller: AppBundle:Temperature:get}
    requirements: 
        id: \d+

check_temp:
    path: "/temperature/check"
    defaults: {_controller: AppBundle:Temperature:check}

get_all_temp:
    path: "temperature/getall"
    defaults: {_controller: AppBundle:Temperature:getAll}

location_index:
    path: "location/index"
    defaults: {_controller: AppBundle:Location:index}

location_json:
    path: "location/json"
    defaults: {_controller: AppBundle:Location:indexJson}

standalone:
    path: "/standalone"
    defaults: 
        _controller: FrameworkBundle:Template:template
        template: standalone/index.html.twig
        maxAge: 86400
        shareAge: 86400

forward:
    path: "/forward"
    defaults: {_controller: AppBundle:Forward:index}

